### ISSUE TITLE
Thoughts about borrowing from the buffer inside Jiter

### ISSUE THREAD

**Issue by nalply** [pydantic/jiter#159]
I stumbled upon some borrowing problem and it caused me thinking a little bit.

Please look at this issue only as me airing out my thoughts. It's not a feature request nor a bug report.

I have this *working* code:

```
  let mut opt_key = jiter.next_object()?.map(|k| k.to_owned());
  while let Some(host_id) = opt_key {
    let host = jiter.next_str()?;
    let prev = hosts.insert(host_id.parse()?, host.parse()?);
    if prev.is_some() {
      err!("duplicate host_id {host_id}")?;
    }
    opt_key = jiter.next_key()?.map(|k| k.to_owned());
  }
```

Here I am reading a JSON file hosts.json of the form `{ "hostid": "host" ..}` into a map. 

I am using Jiter because I want to detect duplicate host ids. *serde_json* and *tinyjson* both happily accept duplicate host ids and use one of the duplicate entries. That's because they rely on a map and don't check the result of the `insert()` method. Why should they at all? Haha.

`err!()` is a macro formatting text into an error message and creating a `Result::Err()`. `host` and `host_id` are parsed to types specific to my application. Both things are not important here. I wanted to show a real-world code snippet, so please excuse that the code is not a reproducible test.

This said, let me tell me about the borrowing problem.

The `next_object()`, `next_str()` and `next_key()` all take `&mut self`.

This causes rustc to say: "cannot borrow \`*jiter\` as mutable more than once at a time" as soon as one still keeps a borrow from a former call when calling another method.

I solved this problem with two `.map(|k| k.to_owned())` incantations.

However this got me thinking: Perhaps there's a conceptual problem? Because it should work? The `&str` value borrows from the buffer and the buffer is immutable?

I realized: There are two borrowing modes going on:

- `&mut self` is needed for advancing the index
- `&self` would suffice for slicing the buffer

but the methods do both and need to apply the stricter mode.

This forces users to clone or to allocate because they can't do a shared borrow of the buffer.

I thought of one possible way. Please understand I am not requesting a feature, only thinking out loud.

Expose the parser from the `Jiter` struct and give it an API that returns ranges to the buffer. Users then slice the buffer themselves. This doesn't conflict with `&mut self` I am quite sure.

**Comment by samuelcolvin** [comment]
Maybe @davidhewitt can add something, but I don't think what you're asking for is possible.

The point is that there are two sorts of strings possible in JSON:
* strings where the underlying bytes are themselves valid as UTF8 data, e.g. `"foobar"`, in this case jiter returns a pointer to the underlying slice of the incoming data
* strings that are not valid as UTF8 - anything that includes escape characters or `\U` unicode symbols e.g. `"foo\nbar"` or `"foo\U1234bar"` - in this case jiter has to build up a new `String` as it can't just return a pointer to the original data, for performance reasons, we reuse a "tape" string each time we need to do this, rather than allocating a new `String`

So the point is that the string methods return a `&str` which can either be a pointer to a slice of the original JSON, or a pointer to the tape.

This is only really possible because rust's borrow checker does exactly the right thing and avoids you keeping a reference to the tape which might later change.

**Comment by nalply** [comment]
Good point, thank you! By the way, I did the backtick thing with code, is this not enough?

**Comment by davidhewitt** [comment]
One slight alternative here is that we could allow the `tape` to be passed in, e.g. `jiter.next_str(&mut tape)`, where the return value could then not depend on a mutable borrow on `jiter` itself, but would still borrow from either the tape or the original source data.

This would be quite limited, as in theory the next "value" could have an unlimited number of strings. But for simple usage this might expose a little bit of extra control.
