### ISSUE TITLE
Consider migrating away from the lexical_core crate

### ISSUE THREAD

**Issue by gotmax23** [pydantic/jiter#49]
Hi! I am the maintainer of pydantic and pydantic-core in Fedora Linux that now require this crate. jitter depends on lexical_core to parse floats. lexical has [multiple soundness/safety issues](https://rustsec.org/advisories/RUSTSEC-2023-0055.html) and is no longer actively maintained. We would thus prefer not to package it in Fedora. Would it be possible for jitter to use a different crate for this purpose?

See also: the list of alternative libraries in [RUSTSEC-2023-0055](https://rustsec.org/advisories/RUSTSEC-2023-0055.html)

**Comment by samuelcolvin** [comment]
Thanks @gotmax23 for letting us know.

Discussion is continuing on #53.

**Comment by decathorpe** [comment]
I *think* you would avoid pulling in the components that have unsafe / unsound code in them by just depending on lexical-parse-float directly instead of using the re-exported functionality in lexical-core. That is also what [ruff](https://github.com/astral-sh/ruff) does. Though of course there's still the tradeoff between the negative performance impact and the fact that the lexical-* crates *all* look unmaintained.
